### PR TITLE
Python 3.4 support

### PR DESCRIPTION
**Pull request by jbenua**
Lib was written in python3.5+, i've made some patches to support python3.4

Changed `async with` to `with (yield from ..)`, `async def` to decorators, `await` to `yield from`

### CODE REVIEW

**Comment by kxepal** [comment]
Why do you need Python 3.4 support at the end of 2017?

**Comment by jbenua** [comment]
Centos 7 with py34 in prod and too busy admins :(

Moreover, [here](https://github.com/shveenkov/aiotarantool/blob/0a416e239098d2dc3effe03a2d30eaefbfc98c45/setup.py#L24) is written about support

**Comment by shveenkov** [comment]
@jbenua, we left 3.4 support a long time ago
https://github.com/shveenkov/aiotarantool/pull/10/files

**Comment by jbenua** [comment]
Many people are still using py26 (thanks God, not me). And 3.4 is still in LTS Ubuntu till April'19.
Do you in Mail department have release problems that differ from IM? If all this doesn't look very reasonably for you, I'll use the fork, no problem

**Pull request closed without merging**
